version: "3"
services: 
    api:
        image: mateozapater/fastapi
        depends_on:
            - postgres
        ports: 
            - 80:8000
        # command: uvicorn app.main:app --host 0.0.0.0 --port 8000
        # env_file:
        #    - ./.env
        environment:
            - DATABASE_HOSTNAME=${DATABASE_HOSTNAME}
            - DATABASE_PORT=${DATABASE_PORT}
            - DATABASE_PASSWORD=${DATABASE_PASSWORD}
            - DATABASE_NAME=${DATABASE_NAME}
            - DATABASE_USERNAME=${DATABASE_USERNAME}
            - SECRET_KEY=${SECRET_KEY}
            - ALGORITHM=${ALGORITHM}
            - ACCESS_TOKEN_EXPIRES_MINUTES=${ACCESS_TOKEN_EXPIRES_MINUTES}
    postgres:
        image: postgres
        environment:
            - POSTGRES_PASSWORD=password123
            - POSTGRES_DB=fastapi
        volumes:
            - postgres-db:/var/lib/postgresql/data

volumes:
    postgres-db: